### PR TITLE
inner-1291:normally close if write error & interval check close timeout

### PR DESCRIPTION
**Pull request by dcy10000**
Signed-off-by: dcy <dcy10000@gmail.com>

Reason:  
  BUG inner-1291:normally close if write error & interval check close timeout
Type:  
  BUG
Influences：  
  close

### CODE REVIEW

**Review by wenyh1 — COMMENTED** [review]
lgtm

**Review by wenyh1 — DISMISSED** [review]

**Comment by dcy10000** [comment]
delay, should also process  the flow control

**Comment by dcy10000** [comment]
ready

**Review by wenyh1 — APPROVED** [review]
lgtm

**Pull request merged**
