### PR TITLE
Support sql statistics

### PR DESCRIPTION
**Pull request by wenyh1**
Reason:  
  Improve #2428 .  
Type:  
  Improve  
Influences：  
   Support sql statistics

### CODE REVIEW

**Comment by wenyh1** [comment]
draft eason: need to improve rwSplit and tx

**Comment by wenyh1** [comment]
resolve conflicts

**Comment by wenyh1** [comment]
It was an accident.

**Comment by wenyh1** [comment]
ignore alerts(10 for Dereferenced variable may be null); 
Maybe third-party tools aren't clever enough.

**Review by PanternBao — APPROVED** [review]
lgtm

**Pull request merged**
