### PR TITLE
#1114 - add TX_PREPARING_STATE state for mysql connection in xa trans…

### LINKED ISSUE #1114: when running sysbench oltp test ,XA transaction can't restore correctly after restarting dble
* **dble version：**  
     2.19.01.0
* **preconditions ：**  
    - 1、 sudo yum install sysbench
   - 2、edit   $SYSBENCH_SCRIPT_HOME/lua-tests/db/oltp.lua ,add `db_query("set xa=1")`  below ` db_query(begin_query)`
  - 3、edit   $SYSBENCH_SCRIPT_HOME/oltp.sh， add `--mysql-ignore-errors=1205,2013,1213,1003,1062`
 - 4、edit  $SYSBENCH_SCRIPT_HOME/conf.sh, configure the correct database information

* **configs：** 

**schema.xml**  

```

<schema name="dbtest">
		<table dataNode="dn1,dn2" name="sbtest1" rule="mod2" />
   </schema>

	<dataNode name="dn1" dataHost="localhost1" database="sysbench_0" />
	<dataNode name="dn2" dataHost="localhost1" database="sysbench_1" />
```

**rule.xml**  

```
<tableRule name="mod2">
		<rule>
			<columns>id</columns>
			<algorithm>hashmod2</algorithm>
		</rule>
	</tableRule>
	<function name="hashmod2" class="Hash">
		<property name="partitionCount">2</property>
		<property name="partitionLength">1</property>
	</function>

```

**server.xml**  

```


```

* **steps：**    
    step1.   execute shell `sh oltp.sh`  on the installed sysbench machine
    step2.  restart dble when sysbench is running
    step3.  stop sysbench
    step4.  execute `xa recover` on the mysql which is used by dble 
* **expect result：**  
    1. empty result, dble can restore all not completed xa transactions.
* **real result：**  
    1. There are still some transactions that have not been released
* **supplements：**  
    1.

/label ~BUG

### PR DESCRIPTION
**Pull request by tankilo**
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix #1114

### CODE REVIEW

**Comment by tankilo** [comment]
> ok

I think you may need to check ISSUE #1114  carefully, yesterday i just tested the scene that xa prepare got explicit error from mysql. I did't have time to check what happened if  the connection to mysql is broken. `XACommitNodesHandler#innerConnectError` must have same problems too.

**Comment by tankilo** [comment]
> ok

I have checked the test scene of 'broken connection when sending xa prepare' and commit again in the PR . 
And i found that in the above situation , dble use `XAAutoRollbackNodesHandler#rollback` to automatically rollback the transaction with a new backend connection. I think users may get confused when they get OK response from the command  `commit` while the DML  is acutally rollbacked. Why not bring the error to the users and let users execute rollback?

```
mysql> set xa = 1;
Query OK, 0 rows affected (0.17 sec)

mysql> begin;
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO xa_test (id) VALUES(1),(2),(3);
Query OK, 3 rows affected (0.15 sec)

mysql> commit;
Query OK, 0 rows affected (17 min 41.85 sec)
```

**Comment by yanhuqing666** [comment]
> > ok
> 
> I have checked the test scene of 'broken connection when sending xa prepare' and commit again in the PR .
> And i found that in the above situation , dble use `XAAutoRollbackNodesHandler#rollback` to automatically rollback the transaction with a new backend connection. I think users may get confused when they get OK response from the command `commit` while the DML is acutally rollbacked. Why not bring the error to the users and let users execute rollback?
> 
> ```
> mysql> set xa = 1;
> Query OK, 0 rows affected (0.17 sec)
> 
> mysql> begin;
> Query OK, 0 rows affected (0.01 sec)
> 
> mysql> INSERT INTO xa_test (id) VALUES(1),(2),(3);
> Query OK, 3 rows affected (0.15 sec)
> 
> mysql> commit;
> Query OK, 0 rows affected (17 min 41.85 sec)
> 
> mysql> select * from xa_test;
> Empty set (0.35 sec)
> ```

may import from #1112 @Baofengqi

**Comment by tankilo** [comment]
> > ok
> 
> I have checked the test scene of 'broken connection when sending xa prepare' and commit again in the PR .
> And i found that in the above situation , dble use `XAAutoRollbackNodesHandler#rollback` to automatically rollback the transaction with a new backend connection. I think users may get confused when they get OK response from the command `commit` while the DML is acutally rollbacked. Why not bring the error to the users and let users execute rollback?
> 
> ```
> mysql> set xa = 1;
> Query OK, 0 rows affected (0.17 sec)
> 
> mysql> begin;
> Query OK, 0 rows affected (0.01 sec)
> 
> mysql> INSERT INTO xa_test (id) VALUES(1),(2),(3);
> Query OK, 3 rows affected (0.15 sec)
> 
> mysql> commit;
> Query OK, 0 rows affected (17 min 41.85 sec)
> 
> mysql> select * from xa_test;
> Empty set (0.35 sec)
> ```

This is due to the judgement condition (`session.getXaState() != TxState.TX_PREPARE_UNCONNECT_STATE`) in  method `com.actiontech.dble.backend.mysql.nio.handler.transaction.xa.XACommitNodesHandler#nextParse`
```
    protected void nextParse() {
        if (this.isFail() && session.getXaState() != TxState.TX_PREPARE_UNCONNECT_STATE) {
            session.getSource().setTxInterrupt(error);
            session.getSource().write(sendData);
            LOGGER.info("nextParse failed:" + error);
        } else {
            commit();
        }
    }
```

I found a more serious problem that whehter you remove the above  judgement condition or not ,in other words ,whether you automatically rollback the transaction or not,  you can't continue to commit the next transaction successfully. I found that the previous XA transaction set `(XACommitNodesHandler)MultiNodeHandler#isFailed` to true when users execute `commit` and the following  XA transaction failed to reset `(XACommitNodesHandler)MultiNodeHandler#isFailed`  to false in method `AbstractCommitNodesHandler#reset`.

**`AbstractCommitNodesHandler#reset` override `MultiNodeHandler#reset`**

com.actiontech.dble.backend.mysql.nio.handler.transaction.AbstractCommitNodesHandler#reset
image

com.actiontech.dble.backend.mysql.nio.handler.MultiNodeHandler#reset
image

```
mysql> set xa = 1;
Query OK, 0 rows affected (0.17 sec)

mysql> begin;
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO xa_test (id) VALUES(1),(2),(3);
Query OK, 3 rows affected (0.13 sec)

mysql> commit;
ERROR 1105 (HY000): err:java.nio.channels.ClosedChannelException
mysql> rollback;
Query OK, 0 rows affected (31.72 sec)

mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> INSERT INTO xa_test (id) VALUES(1),(2),(3);
Query OK, 3 rows affected (0.01 sec)

// 在某个XA PREPARE的时候关闭后端连接
mysql> commit;
Query OK, 0 rows affected (4.28 sec)

mysql> select * from xa_test;
ERROR 1003 (HY000): Transaction error, need to rollback.Reason:[err:java.nio.channels.ClosedChannelException]
```

**Comment by tankilo** [comment]
After i remove method `AbstractCommitNodesHandler#reset`, the above problem is fixed.

```
mysql> set xa = 1;
Query OK, 0 rows affected (0.45 sec)

mysql> begin;
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO xa_test (id) VALUES(1),(2),(3);
Query OK, 3 rows affected (0.40 sec)

mysql> commit;
ERROR 1105 (HY000): err:java.nio.channels.ClosedChannelException
mysql> rollback;
Query OK, 0 rows affected (2.67 sec)

mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> INSERT INTO xa_test (id) VALUES(1),(2),(3);
Query OK, 3 rows affected (0.01 sec)

mysql> commit;
Query OK, 0 rows affected (0.14 sec)

mysql> select * from xa_test;
+----+
| id |
+----+
|  1 |
|  3 |
|  2 |
+----+
3 rows in set (0.07 sec)
```

**Pull request merged**
