### PR TITLE
inner-836:big packet support

### PR DESCRIPTION
**Pull request by dcy10000**
Signed-off-by: dcy <dcy10000@gmail.com>

Reason:  
  BUG inner-836
Type:  
  BUG
Influences：  
   fix xx

### CODE REVIEW

**Comment by ylinzhu** [comment]
src/main/java/com/actiontech/dble/net/mysql/CommandPacket.java
      BufferUtil.writeUB3(buffer, MySQLPacket.MAX_PACKET_SIZE);
            buffer.put(packetId++);
            remain = writeBody(buffer, isFirst, remain);
            service.getSession().getShardingService().nextPacketId();
            //service.getSession().getShardingService().nextPacketId();
            service.writeDirectly(buffer);
            isFirst = false;

remove useless code instead of comments

**Comment by dcy10000** [comment]
ok

**Comment by dcy10000** [comment]
> src/main/java/com/actiontech/dble/net/mysql/CommandPacket.java
> BufferUtil.writeUB3(buffer, MySQLPacket.MAX_PACKET_SIZE);
> buffer.put(packetId++);
> remain = writeBody(buffer, isFirst, remain);
> service.getSession().getShardingService().nextPacketId();
> //service.getSession().getShardingService().nextPacketId();
> service.writeDirectly(buffer);
> isFirst = false;
> 
> remove useless code instead of comments

done

**Review by ylinzhu — APPROVED** [review]
ok

**Pull request merged**
